source 'https://rubygems.org'


group :jekyll_optional_dependencies do
    gem 'jekyll-paginate'
    gem 'kramdown-syntax-coderay'
    gem 'jekyll-sitemap', '~> 1.4'
    gem 'jekyll-feed'
    gem "jekyll", "~> 4.4"
    gem "jekyll-sass-converter", "~> 2.2"
    gem "sassc", "~> 2.4"
end
